---
title: "第十五堂課6-12"
author: "Ulrixon"
date: "6/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
```

```{r}
# 先執行此行輸入學號
readline(prompt = "先執行此行輸入學號") -> studentId 
```
```{r}
if(
  str_detect(studentId,'^[43](1[01][0-9]|9[0-9])[0-9]{5}$',negate=T) # condition: 是否輸入學號正確？
) {
  warning("你所輸入的學號不正確")
}
```

```{r}
if(!require(lubridate)){ # condition: 是否「沒安裝lubridate」？
  install.packages("lubridate")
}
lubridate::ymd_hms("2020-07-01 13:00:00 GMT")
```

```{r}
convert_TaiwanDate2WesternDate <- function(twDate){
  
  if(!require("stringr")){
    install.packages("stringr")
  }
  if(!require("lubridate")){
    install.packages("lubridate")
  }
  
  library(stringr)
  regex_pattern <-
    "(?<=民國)[0-9]+(?=年)"
  
  # 取出民國年，計算西元年
  year <- 
    str_extract(
      twDate,
      regex_pattern)
  westernYear <- as.integer(year)+1911
  
  # 替換民國xx年的xx成西元年數字
  str_replace(
    twDate,
    regex_pattern,  # 要換掉的文字
    as.character(westernYear) # 要替換的內容
  ) -> twDate_reformat
  
  lubridate::ymd(twDate_reformat) -> westernDate
  return(westernDate)
}
```
```{r}
check_package=function(package){
  if(!require(package)){
    install.packages(package)
  }
}
```

```{r}
# 測試
check_package("clipr")
check_package("SOAR")
```

```{r}
askSilly_weather <- function(locationInput,dateInput){
  if(!require("jsonlite")){
    install.packages("jsonlite")
  }
  if(str_detect(locationInput,"^台")){
    str_replace(locationInput,"^台","臺")
  }
  jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->
    pick_MaxT
  (weatherAtLocation$elementName=="MinT") ->
    pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}
```

```{r}
askSilly_weather2 <- function(locationInput,dateInput){
  if(!exists("weather_next36hours")){
      jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
      weather_next36hours
    SOAR::Store(weather_next36hours) # 存在.R_cache environment中
  }  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->
    pick_MaxT
  (weatherAtLocation$elementName=="MinT") ->
    pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}
```

```{r}
system.time(
  askSilly_weather("新北市",today())
)
system.time(
  askSilly_weather("臺北市",today())
)

askSilly_weather("新北市",today())
askSilly_weather("臺北市",today())
```

```{r}
SOAR::Remove(weather_next36hours)
system.time(
  askSilly_weather2("新北市",today())
)
system.time(
  askSilly_weather2("臺北市",today())
)

askSilly_weather2("新北市",today())
askSilly_weather2("臺北市",today())
```

```{r}
myFun <- function(n){
  if(as.logical(n %% 2)){
    fvalue <- -(n+1)/2
  } else {
    fvalue <- n/2
  }
  return(fvalue)
}

myFun(54)
myFun(33)
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/d14j5hp3i5ps657/examSubmissionTimes.json?dl=1") -> examSubmissionTime


head(examSubmissionTime$section)
head(examSubmissionTime$time)
```

```{r}
i<-1
student_i_section <- examSubmissionTime$section[[i]]
student_i_time <- examSubmissionTime$time[[i]]

if(student_i_section=="56"){
  deadline <- lubridate::ymd_hms("2020-05-27 15:00:00", tz="Asia/Taipei")
} else {
  deadline <- lubridate::ymd_hms("2020-05-27 17:00:00", tz="Asia/Taipei")
}

howEarly <- deadline - lubridate::ymd_hms(student_i_time, tz="Asia/Taipei")
print(howEarly)
```

```{r}
compute_howEarly <- function(student_i_section, student_i_time){
  # student_i_section <- examSubmissionTime$section[[i]]
  # student_i_time <- examSubmissionTime$time[[i]]
  
  if(student_i_section=="56"){
    deadline <- lubridate::ymd_hms("2020-05-27 15:00:00", tz="Asia/Taipei")
  } else {
    deadline <- lubridate::ymd_hms("2020-05-27 17:00:00", tz="Asia/Taipei")
  }
  
  howEarly <- deadline - lubridate::ymd_hms(student_i_time, tz="Asia/Taipei")
  # print(howEarly)
  
  return(howEarly)
}
```

```{r}
studentSequence <- 1:length(examSubmissionTime$section)

map(studentSequence,
    ~compute_howEarly(
      examSubmissionTime$section[[.x]],
      examSubmissionTime$time[[.x]])
    ) -> list_howEarly
```

```{r}
as.numeric(readline("請輸入你的成績（整數）： ") )-> grade # 單獨執行
```

```{r}
if(grade >=90){
  print("優")
} else if(grade>=80 & grade<=89){
  print("良")
} else if(grade>=70 & grade<=79){
  print("尚可")
} else {
  print("待加強")
}
```

```{r}
grade <- 80
if(grade >=90){
  print("優")
} else if(grade>=70 & grade<=85){
  print("尚可")
} else if(grade>=75 & grade<=89){
  print("良")
} else {
  print("待加強")
}
```

