---
title: "第十二堂課"
author: "Ulrixon"
date: "5/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)
```

```{r}
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
```

```{r}

jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
map(dance, ~.x$title) ->
  list_titles

View(list_titles)
```
```{r}
map(dance,~length(.x$showInfo)) ->
  list_numberOfShows 
  
View(list_numberOfShows)
```

```{r}
map(dance[[4]]$showInfo, ~ .x$time) ->
  
list_showTimes_dance4
list_showTimes_dance4
```
找出第8個表演的所有場次時間(time)和地點(location):
```{r}
map(dance[[8]]$showInfo, ~ .x$time)
map(dance[[8]]$showInfo, ~ .x$location)
```
```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/od/data/api/67BB3C2B-E7D1-43A7-B872-61B2F082E11B?$format=json", simplifyDataFrame = F) ->
  busRoutes
```
請抓出每條路線的Id(路線代碼)、providerId(業者代碼)、providerName(業者中文名稱)、nameZh(中文名稱)。
```{r}
map(busRoutes,~.x$id)
map(busRoutes,~.x$providerId)
map(busRoutes,~.x$providerName)
map(busRoutes,~.x$nameZh)
```

```{r}
jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
weather_next36hours$cwbopendata$dataset$location$weatherElement[[1]]$elementName 
```
2.1 找出有氣象預報資訊的縣市名稱（locationName欄位）
```{r}
weather_next36hours$cwbopendata$dataset$location$locationName
```
請取出每個縣市有提供的氣象預報因子名稱。（個別名稱的意思要去看欄位說明文件）
```{r}
map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~.x$elementName )
```
2.3 請抓出每縣市在第一個預告時段的
預告開始時間

預告結束時間

這段時間的最高氣溫
```{r}
map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~.x$time[[1]]$startTime)
map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~.x$time[[1]]$endTime)
map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~max(.x$time[[1]]$parameter$parameterValue))
```

```{r}
library(magrittr)
library(stringr)
```
```{r}
# 由cities創出每個元素對應的北部、東部、中部region factor
cities <- factor(c("台北","花蓮","台東","台中"))
levels(cities)
```

```{r}
region <- cities
levels(region) %>% 
  str_replace(.,"台北","北部") %>%
  str_replace(.,"花蓮|台東","東部") %>%
  str_replace(.,"台中","中部") ->
  levels(region)
levels(region)
```

```{r}
jsonlite::fromJSON("https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json") -> covid19

jsonlite::fromJSON(
  "https://www.dropbox.com/s/jckqryeh5zeat5w/regionPopulation.json?dl=1"
) -> population
unlist(population) -> population
```
```{r}
covid19$縣市 <- factor(covid19$縣市)

levels(covid19$縣市) -> levelsInData
population[levelsInData] -> population

population <- sort(population, decreasing=T)
population

newLevels <- names(population)
newLevels

covid19$縣市 <-
  factor(
    covid19$縣市, levels=newLevels
  )

levels(covid19$縣市)
```

```{r}
covid19$縣市 <- factor(covid19$縣市)
levels(covid19$縣市) %>%
population[.] -> population
population <- sort(population, decreasing=T)
population
names(population)%>%
factor(covid19$縣市, levels=.)->covid19$縣市
levels(covid19$縣市)
```

```{r}
population %>% 
  {names(sort(.))} %>%
  
  
  factor(cities, levels=.)  ->cities
```

```{r}
population %>%
  sort() %>%
  names() %>%
  factor(cities, levels=.) -> cities
```

```{r}
remove.packages("magrittr")
install.packages("magrittr")
```

